### ISSUE TITLE
Add Blank empty line between variables and rules (Less File)

### ISSUE THREAD

**Issue by eralmeida** [tierratelematics/code-beautifier#13]
Hello,

I'm not sure this is an issue, but when I format a less file, this is the following result :
@lt-gray: #ddd;
@background-dark: #512DA8;
@background-light: #9575CD;
@background-pale: #D1C4E9;
@carousel-item-height: 300px;
.zero-margin(@pad-up-down: 0px, @pad-left-right: 0px) {
    margin: 0px auto;
    padding: @pad-up-down @pad-left-right;
}

Is there a way to add a new line after the last variable?

**Comment by AjayPoshak** [comment]
I am also facing the same issue. Is there any way we can make that happen?

**Comment by mike7515** [comment]
With the last version(v2.3.0) using this configuration "preserve_newlines": true it add a new line the last variable.
