### ISSUE TITLE
Can't beautify a selection

### ISSUE THREAD

**Issue by electricarts** [tierratelematics/code-beautifier#14]
Indentation or beautify files (sass and css) in VSCode (Mac) drives me nuts. 

After installation of the code-beautifier i've two commands: Format document (option-shift-F) or Format Selection (cmd-K cmd-F). When selecting a a few lines with the mouse and use "Format Selection", it's formatting the whole file. Tried it with sass and css files.

I'm doing something wrong? What do i have to do when i wanna indent or beautify only selected lines?

**Comment by mike7515** [comment]
Fixed in 2.0.3
