### ISSUE TITLE
Respect comment line

### ISSUE THREAD

**Issue by victor-cano** [tierratelematics/code-beautifier#17]
I have been experiencing some issue, when I use this extension with .scss it moves the comments line to the end of the previous line.

**Example:** 
```
body{
width:100%;
}
//more rules
```
become

```
body{
width:100%;
}//more rules
```

**Comment by mike7515** [comment]
Hi,
The extension merges the comments line with the code line only if the code is preceded of spaces or tabs. This is the behaviour of the js-beautify library used for indent the code.
