### ISSUE TITLE
Beautifier.ts: beautify.options type is a 'number'

### ISSUE THREAD

**Issue by rj-xy** [tierratelematics/code-beautifier#18]
The configuration for beautify.options should NOT be a number

`const options = vscode.workspace.getConfiguration('beautify').get<number>("options");`

https://github.com/tierratelematics/code-beautifier/blob/c62dae6d3b34acea8b43b23f917f86001ddd3961/src/Beautifier.ts#L5

**Comment by mike7515** [comment]
Fixed in [2.1.0](https://github.com/mike7515/code-beautifier/tree/2.1.0) version
