### ISSUE TITLE
Selector Separator Newline

### ISSUE THREAD

**Issue by LucasHild** [tierratelematics/code-beautifier#19]
I want to disable, that selectors get their own lines. I tried it with this configuration:

```json
"beautify.options": {
        "css": {
            "selector_separator_newline": false
        }
    }
```

**Comment by mike7515** [comment]
Hi,
the correct extension configuration is:
`"beautify.options": {
        "newline_between_rules": false
    }`

for more options visit [js-beautify](https://github.com/beautify-web/js-beautify#css--html)

**Comment by peabnuts123** [comment]
No, @mike7515. This question is asking about `selector_separator_newline`, not `newline_between_rules`.
