### ISSUE TITLE
Use formatter integration API

### ISSUE THREAD

**Issue by jrieken** [tierratelematics/code-beautifier#2]
In VS Code there is special API for integrating formatters. Take a look at [`registerDocumentFormattingEditProvider`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4072) and [`registerDocumentRangeFormattingEditProvider`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4089). When using these functions to register a formatter, it will be called from the context menu format actions, the default keybindings, and they will automatically be part of the _format on save_ feature. Migrating to that API should be simple and I there to answer questions

**Comment by mike7515** [comment]
Fixed it.
Thanks so much.
