### ISSUE TITLE
should support editorconfig by default

### ISSUE THREAD

**Issue by smnbbrv** [tierratelematics/code-beautifier#21]
Actually subj.

Another advanced feature would be to integrate with linter

**Comment by yblondeau** [comment]
Depending on your config, a possible workaround is to set `beautify.tabSize` to the same value as `indent_size` in your `.editorconfig` file.

**Comment by smnbbrv** [comment]
well, this is not a workaround. This is exactly the opposite of using `.editorconfig`. The latter makes it simple to configure lots of users directly.

I mean yes, problem with tabulations is somehow "solved", but this has nothing to do with editorconfig

**Comment by mike7515** [comment]
In the last version (2.3.1) we removed "tabSize" from the extension options and tabSize is get from the configuration of the active file or from the editor.tabSize
