### ISSUE TITLE
formatting just changed with latest VS Code

### ISSUE THREAD

**Issue by ghost** [tierratelematics/code-beautifier#22]
The following used to format to a single line.  Now I get the below mess.

What do I have to do, to get this to format to a single line like it used to?

Thank you!

Karl

$badge-round-theme: igx-badge-theme( $disable-shadow: false,
$background-color: igx-color($default-palette,
primary),
$border-color: rgb(255,
255,
255),
$text-color: rgb(255,
255,
255));

**Comment by mike7515** [comment]
If you write the code in a single line the format command keep the single line, if you write the code like your comment the format command keep more lines.
