### ISSUE TITLE
beautify.options doesn't work in vscode

### ISSUE THREAD

**Issue by lzl124631x** [tierratelematics/code-beautifier#24]
`ctrl + shift + p` > `open settings (JSON)` > add the following config.

```
{
  // other settings.
    "beautify.options": {
        "newline_between_rules": true
    }
}
```
But it doesn't work even after restarting vscode.

**Comment by card-b** [comment]
I got it to work by passing the arguments like so: 

```
"beautify.options": {
	"css": {
		"indent_with_newline": true,
		"indent_with_tabs": true,
		"newline_between_rules": true,
		"selector_separator_newline": true,
		"preserve_newlines": true
	}
}
```

**Comment by kanlukasz** [comment]
It does not work with me.
An example from CSS:
```
"beautify.options": {
	"css": {
		"indent_with_tabs": true,
	}
}
```
does not work (it still replaces tabs with a space)

I am grateful to the authors of any free addons, but to be honest the readme should be more precise and more detailed... :|

**Comment by mike7515** [comment]
This is the possible extension config
```
{
  indent_size?: number;
  indent_char?: string;
  eol?: string;
  indent_level?: number;
  indent_with_tabs?: boolean;
  preserve_newlines?: boolean;
  max_preserve_newlines?: number;
  jslint_happy?: boolean;
  space_after_anon_function?: boolean;
  brace_style?: 'collapse-preserve-inline' | 'collapse' | 'expand' | 'end-expand' | 'none';
  keep_array_indentation?: boolean;
  keep_function_indentation?: boolean;
  space_before_conditional?: boolean;
  space_in_empty_paren?: boolean;
  break_chained_methods?: boolean;
  eval_code?: boolean;
  unescape_strings?: boolean;
  wrap_line_length?: number;
  wrap_attributes?: 'auto' | 'force';
  wrap_attributes_indent_size?: number;
  end_with_newline?: boolean;
}
```

**Comment by adhirajsinghchauhan** [comment]
@mike7515 Why was this issue closed? The problem hasn't been fixed, it still exists with the latest version of your library.

**Comment by kanlukasz** [comment]
@adhirajsinghchauhan Don't waste time on this plugin. The author does not care about the development of the plugin and the professional handling of tickets. Documentation is also a misunderstanding. I recommend [Prettier](https://github.com/prettier/prettier-vscode) or [Beautify](https://github.com/HookyQR/VSCodeBeautify) for you
