### ISSUE TITLE
Would you change the command?

### ISSUE THREAD

**Issue by TonyPythoneer** [tierratelematics/code-beautifier#3]
It's because I find [Pug beautify ](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-pugbeautify) command calls `Beautify pug/jade`.

I hope this plugin provides command can be more clearly, too.

Personally, I suggest it call `Beautify css/sass/scss/less`.

How do you think?

**Comment by mike7515** [comment]
I changed the extension's display name.
Thanks

**Comment by TonyPythoneer** [comment]
@mike7515 I doesn't mean display name.
I said I hope the command gets changed. It's because the command is `Beautify this code`, not `Beautify css/sass/scss/less`.

**Comment by mike7515** [comment]
Thanks and sorry again.
In extension's version `1.6.1` the command name is `Beautify css/sass/scss/less`.

**Comment by TonyPythoneer** [comment]
Your ext is very helpful. 👍
