### ISSUE TITLE
Formatting of addition operator in less can break rules

### ISSUE THREAD

**Issue by jamietre** [tierratelematics/code-beautifier#4]
This code in less:

    @floorStackHeightOffSet: 2*@headerHeight + @modalHeaderHeight + @rowheight;

was reformatted to

      @floorStackHeightOffSet: 2*@headerHeight +@modalHeaderHeight +@rowheight;

There needs to be a space between the operands and the operator, or it apparently interprets the + as "positive" and not an operator.

**Comment by mike7515** [comment]
Fixed in the last release 1.7.2
